'use client';
import React, { useCallback, useEffect, useState } from 'react';
import { Check, X } from 'lucide-react';
import { Approval, turbohermes } from '@/lib/turbohermes-client';
import { State, TurboHeader } from '@/components/TurboHermesShell';
export default function ApprovalsView() {
 const [items,setItems]=useState<Approval[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [busy,setBusy]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError(null);try{setItems(await turbohermes.approvals())}catch(e){setError(e instanceof Error?e.message:'Unable to load approvals')}finally{setLoading(false)}},[]);
 useEffect(()=>{load();const t=window.setInterval(load,30000);return()=>window.clearInterval(t)},[load]);
 const decide=async(id:string, approve:boolean)=>{setBusy(id);try{await (approve?turbohermes.approve(id):turbohermes.reject(id));setItems(x=>x.map(a=>a.id===id?{...a,status:approve?'approved':'rejected'}:a))}catch(e){setError(e instanceof Error?e.message:'Action failed')}finally{setBusy('')}};
 return <div><TurboHeader eyebrow="TurboHermes / human gates" title="Approval requests" current="/turbohermes/approvals"/><main className="p-6"><State loading={loading} error={error} empty={!items.length} onRetry={load}><div className="overflow-hidden rounded-lg border border-border bg-card">{items.map(a=><article key={a.id} data-testid={`approval-${a.id}`} className="flex flex-col gap-4 border-b border-border p-5 last:border-0 md:flex-row md:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-medium">{a.action}</h2><span className="rounded-full bg-muted px-2 py-0.5 text-2xs uppercase text-muted-foreground">{a.status}</span></div><p className="mt-1 text-sm text-muted-foreground">{a.reason || 'No reason supplied.'}</p><p className="mt-2 text-xs text-muted-foreground">ID {a.id}{a.expiresAt && ` · expires ${new Date(a.expiresAt).toLocaleString()}`}</p></div>{a.status==='pending'&&<div className="flex gap-2"><button disabled={busy===a.id} onClick={()=>decide(a.id,false)} className="btn-secondary flex items-center gap-1 px-3 py-2 text-xs"><X size={14}/>Reject</button><button disabled={busy===a.id} onClick={()=>decide(a.id,true)} className="btn-primary flex items-center gap-1 px-3 py-2 text-xs"><Check size={14}/>Approve</button></div>}</article>)}</div></State></main></div>
}