'use client';
import React, { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowUpRight, RefreshCw, ShieldAlert } from 'lucide-react';
import { turbohermes, Approval, Health, Run } from '@/lib/turbohermes-client';
import { State, Stat, TurboHeader } from '@/components/TurboHermesShell';

export default function TurboOverview() {
  const [health, setHealth] = useState<Health | null>(null); const [approvals, setApprovals] = useState<Approval[]>([]); const [runs, setRuns] = useState<Run[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const [h, a, r] = await Promise.all([turbohermes.health(), turbohermes.approvals(), turbohermes.runs()]); setHealth(h); setApprovals(a); setRuns(r); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load operational data'); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); const timer = window.setInterval(load, 30000); return () => window.clearInterval(timer); }, [load]);
  return <div><TurboHeader eyebrow="TurboHermes / control plane" title="Operational overview" current="/turbohermes" /><main className="space-y-6 p-6">
    <div className="flex items-center justify-between"><p className="max-w-2xl text-sm text-muted-foreground">A private operating surface for the Agency Media Geek orchestrator, approvals, and knowledge system.</p><button onClick={load} className="btn-secondary flex items-center gap-2 px-3 py-2 text-xs"><RefreshCw size={14} />Refresh</button></div>
     <State loading={loading} error={error} empty={false} onRetry={load}><section className="grid grid-cols-2 gap-3 xl:grid-cols-4"><Stat label="Control plane" value={health?.status || 'Unknown'} tone={health?.status === 'healthy' || health?.status === 'ok' ? 'good' : 'warn'} detail={health?.version ? `v${health.version}` : 'Health endpoint'} /><Stat label="Open approvals" value={approvals.filter((a) => a.status === 'pending').length} tone="warn" detail="Human attention required" /><Stat label="Active runs" value={runs.filter((r) => !['completed', 'failed'].includes(r.state)).length} detail={`${runs.length} total observed`} /><Stat label="Environment" value={String(health?.environment || 'Private')} detail="Bearer authenticated" /></section></State>
    <div className="grid gap-4 lg:grid-cols-[1.1fr_.9fr]"><section className="rounded-lg border border-border bg-card p-5"><div className="mb-4 flex items-center justify-between"><h2 className="font-medium">Attention queue</h2><Link href="/turbohermes/approvals" className="text-xs text-primary">View approvals <ArrowUpRight className="inline" size={13} /></Link></div>{approvals.filter((a) => a.status === 'pending').slice(0, 4).map((a) => <div key={a.id} className="flex items-center gap-3 border-t border-border py-3"><ShieldAlert className="text-amber-400" size={16} /><div className="min-w-0 flex-1"><p className="truncate text-sm text-foreground">{a.action}</p><p className="truncate text-xs text-muted-foreground">{a.reason || 'Approval requested'}</p></div><span className="text-2xs uppercase text-amber-400">Pending</span></div>)}{approvals.filter((a) => a.status === 'pending').length === 0 && <p className="py-8 text-center text-sm text-muted-foreground">No approvals waiting.</p>}</section>
      <section className="rounded-lg border border-border bg-card p-5"><div className="mb-4 flex items-center justify-between"><h2 className="font-medium">Latest runs</h2><Link href="/turbohermes/runs" className="text-xs text-primary">Open runs <ArrowUpRight className="inline" size={13} /></Link></div>{runs.slice(0, 5).map((r) => <div key={r.id} className="flex items-center justify-between border-t border-border py-3"><div className="min-w-0"><p className="truncate text-sm">{r.goal}</p><p className="text-xs text-muted-foreground">{r.stage || 'Orchestrator'} · {r.state}</p></div><span className="text-2xs text-muted-foreground">{r.risk || 'normal'}</span></div>)}</section></div>
  </main></div>;
}